version: '3.8'


services:
  chatapp:
    build: ./
    container_name: chatapp
    restart: always
    ports:
      - 9008:9008

    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1

    entrypoint: ["python", "manage.py", "runserver", "0.0.0.0:9008"]


  chatredis:
    image: redis:alpine
    container_name: chatredis
    restart: always