# Generated by Django 4.2.5 on 2023-09-19 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_topic_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.topic'),
            preserve_default=False,
        ),
    ]
